name: Convert Clash Rules to Singbox

on:
  push:
    branches:
      - master
    paths:
      - 'rule/Clash/**'
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次

env:
  SING_BOX_RULESET_VERSION: 2 # sing-box rule-set version

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以便正确处理文件
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Install sing-box
        run: |
          SING_BOX_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep -Po '"tag_name": "\K[^"]*')
          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION/v/}-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          sudo mv "sing-box-${SING_BOX_VERSION/v/}-linux-amd64/sing-box" /usr/local/bin/
          rm -rf sing-box.tar.gz "sing-box-${SING_BOX_VERSION/v/}-linux-amd64"
          sing-box version
      
      - name: Convert Rules
        env:
          RULESET_VERSION: ${{ env.SING_BOX_RULESET_VERSION }}
        run: |
          python user_scripts/convert_to_singbox.py
      
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rule/Singbox/
          git commit -m "chore: update singbox rules [skip ci]" || exit 0
          git push
